apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    name: server
spec:
  containers:
  - name: server
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
spec:
  ports:
    # the port that this service should serve on
  - port: 2345
    targetPort: 80
  selector:
    name: server
  clusterIP: 10.0.0.201
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dialer
  labels:
    name: dialer
spec:
  replicas: 10
  template:
    metadata:
      name: dialer
      labels:
        name: dialer
    spec:
      containers:
      - name: dialer
        image: asymmetric/dialer
        args:
          - dialer
          - "10.0.0.201:2345"
          - "10"
