apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: client
spec:
  containers:
  - name: client
    image: busybox
    args:
      - '/bin/sh'
      - '-c'
      - "sleep 10000"
---
apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    name: server
spec:
  containers:
  - name: server
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: server
