---
apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    name: server
spec:
  containers:
  - name: server
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: server
spec:
  ports:
    # the port that this service should serve on
  - port: 2345
    targetPort: 80
  selector:
    name: server
  clusterIP: 10.0.0.201
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    name: client
spec:
  containers:
  - name: client
    image: busybox
    args:
      - '/bin/sh'
      - '-c'
      - "sleep 10000"
---
apiVersion: v1
kind: Pod
metadata:
  name: clienttosvc
  labels:
    name: clienttosvc
spec:
  containers:
  - name: clienttosvc
    image: busybox
    args:
      - '/bin/sh'
      - '-c'
      - "date ; sleep 5 ; (sleep 70 ; echo 'GET /' ) | nc 10.0.0.201 2345 ; date; sleep 10000 ; date"
---
apiVersion: v1
kind: Pod
metadata:
  name: clienttosvcshortlived
  labels:
    name: clienttosvcshortlived
spec:
  containers:
  - name: clienttosvcshortlived
    image: busybox
    args:
      - '/bin/sh'
      - '-c'
      - "date ; while sleep 2 ; do (sleep 10 ; echo 'GET /')  | nc 10.0.0.201 2345 ; date ; done"
---
apiVersion: v1
kind: Pod
metadata:
  name: client2inet
  labels:
    name: client2inet
spec:
  containers:
  - name: client2inet
    image: busybox
    args:
      - '/bin/sh'
      - '-c'
      - "date ; while sleep 2 ; do (sleep 10 ; echo 'GET /')  | nc ya.ru 80 ; date ; done"
